ZUNO_SETUP_DEBUG_MODE(DEBUG_ON);
ZUNO_SETUP_SLEEPING_MODE(ZUNO_SLEEPING_MODE_ALWAYS_AWAKE);
ZUNO_DISABLE(SERVICE_LEDS);

ZUNO_DYNAMIC_CHANNELS(32);

ZUNO_ENABLE(WITH_CC_SWITCH_MULTILEVEL SWML_STARTSTOPCALLBACK=zunoSWMLCallback USER_STARTSTOPCALLBACK);

//WITH_GENERAL_CHANNEL_VALUES
//#include "OddSoftSer.h"
#include "Logic.h"

void setup() {
  real_setup();
}

void loop() { // run over and over
	real_loop();
}
